'use client';

import Link from 'next/link';
import { Building2, ArrowLeft, FileText, Scale, AlertTriangle, CheckCircle, Users, CreditCard, Gavel, Shield } from 'lucide-react';
import { Footer } from '@/components/layout/Footer';

export default function TermsOfServicePage() {
  const lastUpdated = 'February 23, 2026';
  const effectiveDate = 'February 23, 2026';

  const sections = [
    {
      id: 'acceptance',
      icon: <CheckCircle className="w-5 h-5" />,
      title: 'Acceptance of Terms',
      content: `By accessing or using the LIMIT platform ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you may not access or use the Service.

These Terms constitute a legally binding agreement between you ("User," "you," or "your") and LIMIT Platform ("LIMIT," "we," "us," or "our"). We reserve the right to modify these Terms at any time. Continued use of the Service after modifications constitutes acceptance of the updated Terms.

You must be at least 18 years of age and have the legal capacity to enter into these Terms. If you are using the Service on behalf of an organization, you represent that you have authority to bind that organization to these Terms.`
    },
    {
      id: 'service-description',
      icon: <FileText className="w-5 h-5" />,
      title: 'Service Description',
      content: `LIMIT is a software-as-a-service (SaaS) platform that provides automated GDCR (General Development Control Regulations) 2017 compliance analysis for building projects in Gujarat, India.

**Core Features Include:**
- Automated calculation of Floor Space Index (FSI), setbacks, building height, and other regulatory parameters
- Generation of compliance reports with GDCR clause references
- Project management and data storage
- Bulk analysis capabilities for multiple sites

**Service Limitations:**
The Service is designed as an advisory tool to assist architects, developers, and construction professionals. It does not replace professional architectural, engineering, or legal services. All calculations and recommendations should be independently verified.`
    },
    {
      id: 'advisory-disclaimer',
      icon: <AlertTriangle className="w-5 h-5" />,
      title: 'Advisory Disclaimer',
      content: `**IMPORTANT: PLEASE READ THIS SECTION CAREFULLY**

The LIMIT platform is provided as an ADVISORY TOOL ONLY. All calculations, reports, and recommendations generated by the Service are for informational and reference purposes and should not be considered as professional architectural, engineering, or legal advice.

**You Acknowledge and Agree That:**

1. **Not a Substitute for Professional Services:** The Service does not replace the need for licensed architects, structural engineers, or other qualified professionals. All building plans must be prepared and certified by appropriately licensed professionals.

2. **Verification Required:** All calculations and recommendations must be independently verified with relevant local authorities, including but not limited to municipal corporations, town planning departments, and building permission authorities.

3. **Regulatory Changes:** Building regulations may change. While we strive to keep our database current, we do not guarantee that our calculations reflect the most recent regulatory amendments.

4. **Site-Specific Factors:** The Service may not account for all site-specific conditions, local variations, or special circumstances that may affect regulatory compliance.

5. **No Guarantee of Approval:** Using our Service does not guarantee approval of building permits or compliance certificates from any governmental authority.

6. **Professional Judgment:** Final decisions regarding building design and compliance must be made by qualified professionals exercising their own judgment.

**LIMIT SHALL NOT BE HELD LIABLE FOR ANY DECISIONS MADE OR ACTIONS TAKEN BASED ON THE INFORMATION PROVIDED BY THE SERVICE.**`
    },
    {
      id: 'user-responsibilities',
      icon: <Users className="w-5 h-5" />,
      title: 'User Responsibilities',
      content: `**Account Security:**
- You are responsible for maintaining the confidentiality of your account credentials
- You must notify us immediately of any unauthorized access to your account
- You are responsible for all activities conducted through your account

**Accurate Information:**
- You agree to provide accurate, complete, and current information when using the Service
- You acknowledge that inaccurate input data will result in inaccurate calculations
- You are responsible for verifying that all input parameters match actual site conditions

**Acceptable Use:**
- You will use the Service only for lawful purposes and in accordance with these Terms
- You will not attempt to reverse engineer, decompile, or extract source code from the Service
- You will not use the Service to violate any applicable laws or regulations
- You will not share your account access with unauthorized users
- You will not attempt to circumvent any usage limits or access controls

**Professional Standards:**
- If you are a licensed professional, you agree to use the Service in accordance with applicable professional standards and ethics
- You will not represent LIMIT-generated reports as certified professional documents unless appropriately verified and certified by a licensed professional`
    },
    {
      id: 'intellectual-property',
      icon: <Shield className="w-5 h-5" />,
      title: 'Intellectual Property',
      content: `**Our Intellectual Property:**
The Service, including its design, features, algorithms, source code, documentation, and all related intellectual property, is owned by LIMIT Platform and protected by copyright, trademark, and other intellectual property laws.

You are granted a limited, non-exclusive, non-transferable license to use the Service for its intended purpose during your subscription period.

**Your Data:**
You retain ownership of all data and information you input into the Service. By using the Service, you grant us a limited license to process your data solely to provide the Service functionality.

**Generated Reports:**
Reports generated by the Service are for your use. You may share these reports with clients, authorities, and other stakeholders, provided you include appropriate disclaimers about the advisory nature of the content.

**Feedback:**
Any feedback, suggestions, or ideas you provide about the Service may be used by us without obligation or compensation to you.`
    },
    {
      id: 'payment-terms',
      icon: <CreditCard className="w-5 h-5" />,
      title: 'Payment & Subscription',
      content: `**Pricing:**
Current pricing and subscription plans are displayed on our website. Prices are subject to change with reasonable notice to existing subscribers.

**Free Tier:**
We may offer a free tier with limited features or usage. Free tier terms may be modified or discontinued at any time.

**Paid Subscriptions:**
- Paid subscriptions are billed in advance on a monthly or annual basis
- Payment is processed through our third-party payment processor
- You authorize us to charge your payment method for all applicable fees

**Refunds:**
- We do not provide refunds for partial subscription periods
- Refund requests will be evaluated on a case-by-case basis at our discretion
- If you believe you are entitled to a refund, contact support@limitplatform.com

**Account Suspension:**
We reserve the right to suspend or terminate accounts for non-payment or violation of these Terms.`
    },
    {
      id: 'limitation-liability',
      icon: <Scale className="w-5 h-5" />,
      title: 'Limitation of Liability',
      content: `**Disclaimer of Warranties:**
THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, OR NON-INFRINGEMENT.

**Limitation of Liability:**
TO THE MAXIMUM EXTENT PERMITTED BY LAW, LIMIT SHALL NOT BE LIABLE FOR:
- Any indirect, incidental, special, consequential, or punitive damages
- Loss of profits, revenue, data, or business opportunities
- Costs of substitute services
- Any damages arising from the use or inability to use the Service
- Any decisions made or actions taken based on information provided by the Service
- Any errors, inaccuracies, or omissions in calculations or reports
- Building permit denials, regulatory penalties, or construction issues

**Maximum Liability:**
In no event shall our total liability exceed the amount you paid for the Service in the twelve (12) months preceding the claim.

**Indemnification:**
You agree to indemnify and hold harmless LIMIT and its officers, directors, employees, and agents from any claims, damages, or expenses arising from your use of the Service or violation of these Terms.`
    },
    {
      id: 'termination',
      icon: <Gavel className="w-5 h-5" />,
      title: 'Termination',
      content: `**By You:**
You may terminate your account at any time through your account settings or by contacting support. Upon termination:
- Your access to the Service will cease immediately
- Your data will be retained for 30 days before permanent deletion
- No refunds will be provided for unused subscription periods

**By Us:**
We may suspend or terminate your account immediately if:
- You violate these Terms
- You fail to pay applicable fees
- Your use poses a security risk to the Service or other users
- We are required to do so by law

**Effect of Termination:**
Upon termination, your right to use the Service ceases immediately. Provisions that by their nature should survive termination (including disclaimers, limitations of liability, and indemnification) shall survive.`
    },
    {
      id: 'governing-law',
      icon: <Scale className="w-5 h-5" />,
      title: 'Governing Law & Disputes',
      content: `**Governing Law:**
These Terms shall be governed by and construed in accordance with the laws of India, without regard to conflict of law principles.

**Jurisdiction:**
Any disputes arising from these Terms or the Service shall be subject to the exclusive jurisdiction of the courts in Ahmedabad, Gujarat, India.

**Dispute Resolution:**
Before initiating any legal proceedings, you agree to attempt to resolve disputes informally by contacting us at legal@limitplatform.com. We will attempt to resolve disputes within 30 days.

**Class Action Waiver:**
You agree that any dispute resolution proceedings will be conducted only on an individual basis and not in a class, consolidated, or representative action.`
    },
    {
      id: 'contact',
      icon: <FileText className="w-5 h-5" />,
      title: 'Contact Information',
      content: `For questions about these Terms of Service, please contact us:

**LIMIT Platform**
Email: legal@limitplatform.com
Support: support@limitplatform.com

Address:
Ahmedabad, Gujarat
India 380015

We aim to respond to all inquiries within 2-3 business days.`
    }
  ];

  return (
    <div className="min-h-screen bg-[var(--bg-primary)] text-[var(--text-primary)]">
      {/* Ambient background */}
      <div className="fixed inset-0 bg-gradient-mesh pointer-events-none" />

      {/* Navigation */}
      <header className="relative z-50 border-b border-[var(--border-subtle)]">
        <nav className="container-wide py-4">
          <div className="flex items-center justify-between">
            <Link href="/" className="flex items-center gap-3 group">
              <div className="w-10 h-10 rounded-[var(--radius-lg)] bg-gradient-to-br from-[var(--accent-primary)] to-[var(--accent-secondary)] flex items-center justify-center shadow-lg transition-transform group-hover:scale-105">
                <Building2 className="w-5 h-5 text-[var(--bg-primary)]" />
              </div>
              <span className="text-xl font-bold tracking-tight">LIMIT</span>
            </Link>
            <Link
              href="/"
              className="flex items-center gap-2 text-sm text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-colors"
            >
              <ArrowLeft className="w-4 h-4" />
              Back to Home
            </Link>
          </div>
        </nav>
      </header>

      {/* Hero Section */}
      <section className="relative py-16 md:py-24 border-b border-[var(--border-subtle)]">
        <div className="container-base text-center">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-[var(--bg-secondary)] border border-[var(--border-default)] mb-6">
            <Scale className="w-4 h-4 text-[var(--accent-primary)]" />
            <span className="text-sm font-mono text-[var(--text-secondary)]">Legal Agreement</span>
          </div>
          <h1 className="heading-1 mb-4">Terms of Service</h1>
          <p className="body-large max-w-2xl mx-auto mb-6">
            Please read these terms carefully before using the LIMIT platform. By using our service, you agree to be bound by these terms.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 text-sm text-[var(--text-muted)]">
            <span>Effective Date: {effectiveDate}</span>
            <span className="hidden sm:block">|</span>
            <span>Last Updated: {lastUpdated}</span>
          </div>
        </div>
      </section>

      {/* Important Notice */}
      <section className="relative py-8 border-b border-[var(--border-subtle)] bg-[var(--warning-bg)]">
        <div className="container-base">
          <div className="flex items-start gap-4">
            <AlertTriangle className="w-6 h-6 text-[var(--warning)] flex-shrink-0 mt-0.5" />
            <div>
              <h2 className="font-semibold text-[var(--warning)] mb-2">Important Notice</h2>
              <p className="text-sm text-[var(--text-secondary)] leading-relaxed">
                LIMIT is an advisory tool only. All calculations and reports are for reference purposes and must be verified with local authorities and licensed professionals before proceeding with any construction work. By using this service, you acknowledge and accept this limitation.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Table of Contents */}
      <section className="relative py-12 border-b border-[var(--border-subtle)]">
        <div className="container-base">
          <h2 className="text-sm font-mono uppercase tracking-wider text-[var(--text-tertiary)] mb-6">
            Table of Contents
          </h2>
          <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
            {sections.map((section, index) => (
              <a
                key={section.id}
                href={`#${section.id}`}
                className="flex items-center gap-2 p-3 rounded-[var(--radius-lg)] bg-[var(--bg-secondary)] border border-[var(--border-subtle)] hover:border-[var(--border-strong)] hover:bg-[var(--bg-tertiary)] transition-all text-sm text-[var(--text-secondary)] hover:text-[var(--text-primary)]"
              >
                <span className="font-mono text-[var(--text-muted)] text-xs">{String(index + 1).padStart(2, '0')}</span>
                <span className="truncate">{section.title}</span>
              </a>
            ))}
          </div>
        </div>
      </section>

      {/* Content Sections */}
      <section className="relative py-16">
        <div className="container-base">
          <div className="space-y-16">
            {sections.map((section, index) => (
              <div
                key={section.id}
                id={section.id}
                className="scroll-mt-24"
              >
                <div className="flex items-center gap-3 mb-6">
                  <div className="w-10 h-10 rounded-[var(--radius-lg)] bg-[var(--accent-subtle)] flex items-center justify-center text-[var(--accent-primary)]">
                    {section.icon}
                  </div>
                  <div>
                    <span className="text-xs font-mono text-[var(--text-muted)] uppercase tracking-wider">
                      Section {String(index + 1).padStart(2, '0')}
                    </span>
                    <h2 className="heading-3">{section.title}</h2>
                  </div>
                </div>
                <div className="pl-0 md:pl-[52px]">
                  <div className="prose prose-invert max-w-none">
                    {section.content.split('\n\n').map((paragraph, pIndex) => (
                      <p
                        key={pIndex}
                        className="text-[var(--text-secondary)] leading-relaxed mb-4 whitespace-pre-line"
                        dangerouslySetInnerHTML={{
                          __html: paragraph
                            .replace(/\*\*(.*?)\*\*/g, '<strong class="text-[var(--text-primary)] font-semibold">$1</strong>')
                            .replace(/- (.*?)(?=\n|$)/g, '<span class="block pl-4 relative before:content-[\'•\'] before:absolute before:left-0 before:text-[var(--accent-primary)]">$1</span>')
                        }}
                      />
                    ))}
                  </div>
                </div>
                {index < sections.length - 1 && (
                  <div className="divider mt-16" />
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Footer */}
      <Footer />
    </div>
  );
}
